swagger: "2.0"
info:
  title: Swagger API
  description: 使用swagger测试爽歪歪.
  version: 1.0.0
  contact:
    email: 2929712050@qq.com
basePath: /v1
paths:
  /article/:
    post:
      tags:
      - login
      description: 发布文章
      operationId: ArticleController.发布文章
      parameters:
      - in: formData
        name: title
        description: 文章标题
        required: true
        type: string
        default: hello world
      - in: formData
        name: userId
        description: 用户id
        required: true
        type: integer
        format: int64
        default: "0"
      - in: formData
        name: content
        description: 文章内容
        required: true
        type: string
        default: hello wordl content
      - in: formData
        name: publishAt
        description: 发布日期
        required: true
        schema:
          $ref: '#/definitions/date'
        default: ""
      - in: formData
        name: viewCount
        description: 浏览次数
        required: true
        type: integer
        format: int64
        default: "100"
      responses:
        "200":
          description: '{int}'
        "403":
          description: body is empty
  /login/:
    post:
      tags:
      - login
      description: 发布文章
      operationId: ArticleController.发布文章
      parameters:
      - in: formData
        name: title
        description: 文章标题
        required: true
        type: string
        default: hello world
      - in: formData
        name: userId
        description: 用户id
        required: true
        type: integer
        format: int64
        default: "0"
      - in: formData
        name: content
        description: 文章内容
        required: true
        type: string
        default: hello wordl content
      - in: formData
        name: publishAt
        description: 发布日期
        required: true
        schema:
          $ref: '#/definitions/date'
        default: ""
      - in: formData
        name: viewCount
        description: 浏览次数
        required: true
        type: integer
        format: int64
        default: "100"
      responses:
        "200":
          description: '{int}'
        "403":
          description: body is empty
  /user/:
    get:
      tags:
      - user
      description: 获取用户列表的
      responses:
        "200":
          description: 请求成功
        "1101":
          description: 外部传入参数错误
        "1102":
          description: 请求出错
    post:
      tags:
      - user
      description: 创建用户
      operationId: UserController.创建用户
      parameters:
      - in: formData
        name: username
        description: 用户名
        required: true
        type: string
        default: ant
      - in: formData
        name: password
        description: 密码
        required: true
        type: string
        default: "123"
      responses:
        "200":
          description: 请求成功
        "1101":
          description: 外部传入参数错误
        "1102":
          description: 请求出错
definitions:
  date:
    title: date
    type: object
tags:
- name: user
  description: |
    Operations about User
- name: article
  description: |
    Operations about Article
- name: login
  description: |
    Operations about Article
