swagger: "2.0"
info:
  title: Swagger API
  description: 使用swagger测试爽歪歪.
  version: 1.0.0
  contact:
    email: 2929712050@qq.com
basePath: /v1
paths:
  /article/:
    get:
      tags:
      - article
      description: 获取文章列表
      responses:
        "200":
          description: 请求成功
        "1102":
          description: 请求出错
    post:
      tags:
      - article
      description: 发布文章
      operationId: ArticleController.发布文章
      parameters:
      - in: formData
        name: title
        description: 文章标题
        required: true
        type: string
        default: hello world
      - in: formData
        name: userId
        description: 用户id
        required: true
        type: integer
        format: int64
        default: "0"
      - in: formData
        name: content
        description: 文章内容
        required: true
        type: string
        default: hello world content
      - in: formData
        name: publishAt
        description: 发布日期时间戳
        required: true
        type: integer
        format: int64
        default: ""
      - in: formData
        name: categoryId
        description: 分类id
        required: true
        type: integer
        format: int64
        default: ""
      - in: formData
        name: tagId
        description: 标签id
        required: true
        type: integer
        format: int64
        default: "100"
      responses:
        "200":
          description: 请求成功
        "1101":
          description: 外部传入参数错误
        "1102":
          description: 请求出错
  /article/{id}:
    get:
      tags:
      - article
      description: 删除文章
      responses:
        "200":
          description: 请求成功
        "1102":
          description: 请求出错
    put:
      tags:
      - article
      description: 更新文章
      operationId: ArticleController.更新文章
      parameters:
      - in: formData
        name: title
        description: 文章标题
        required: true
        type: string
        default: hello world
      - in: formData
        name: userId
        description: 用户id
        required: true
        type: integer
        format: int64
        default: "0"
      - in: formData
        name: content
        description: 文章内容
        required: true
        type: string
        default: hello world content
      - in: formData
        name: publishAt
        description: 发布日期时间戳
        required: true
        type: integer
        format: int64
        default: ""
      - in: formData
        name: categoryId
        description: 分类id
        required: true
        type: integer
        format: int64
        default: ""
      - in: formData
        name: tagId
        description: 标签id
        required: true
        type: integer
        format: int64
        default: "100"
      responses:
        "200":
          description: 请求成功
        "1101":
          description: 外部传入参数错误
        "1102":
          description: 请求出错
  /category/:
    get:
      tags:
      - category
      description: 获取分类列表
      responses:
        "200":
          description: 请求成功
        "1102":
          description: 请求出错
    post:
      tags:
      - category
      description: 创建分类
      operationId: CategoryController.创建分类
      parameters:
      - in: formData
        name: categoryName
        description: 分类名字
        required: true
        type: string
        default: 前端
      responses:
        "200":
          description: 请求成功
        "1101":
          description: 外部传入参数错误
        "1102":
          description: 请求出错
        "1109":
          description: 分类已存在
  /category/{id}:
    get:
      tags:
      - category
      description: 获取单个分类数据
      responses:
        "200":
          description: 请求成功
        "1102":
          description: 请求出错
    put:
      tags:
      - category
      description: 更新分类
      operationId: CategoryController.更新分类
      parameters:
      - in: path
        name: id
        description: 分类id
        required: true
        type: string
        default: 分类id
      - in: formData
        name: tagName
        description: 标签名字
        required: true
        type: string
        default: javascript
      responses:
        "200":
          description: 请求成功
        "1101":
          description: 外部传入参数错误
        "1102":
          description: 请求出错
        "1108":
          description: 标签名已存在
  /login/:
    post:
      tags:
      - login
      description: 用户登录
      operationId: LoginController.用户登录
      parameters:
      - in: formData
        name: username
        description: 用户名
        required: true
        type: string
        default: ant
      - in: formData
        name: password
        description: 密码
        required: true
        type: string
        default: "123"
      responses:
        "200":
          description: 登录成功
        "1101":
          description: 参数错误
        "1102":
          description: 请求出错
        "1104":
          description: 用户名不存在
        "1105":
          description: 用户名或者密码错误
  /logout/:
    post:
      tags:
      - logout
      description: 用户登出
      operationId: LogoutController.用户登出
      responses:
        "200":
          description: 登录成功
        "1101":
          description: 参数错误
        "1102":
          description: 请求出错
  /tag/:
    get:
      tags:
      - tag
      description: 获取标签列表
      responses:
        "200":
          description: 请求成功
        "1101":
          description: 外部传入参数错误
        "1102":
          description: 请求出错
    post:
      tags:
      - tag
      description: 创建标签
      operationId: TagController.创建标签
      parameters:
      - in: formData
        name: tagName
        description: 标签名字
        required: true
        type: string
        default: javascript
      responses:
        "200":
          description: 请求成功
        "1101":
          description: 外部传入参数错误
        "1102":
          description: 请求出错
        "1108":
          description: 标签名已存在
  /tag/{id}:
    get:
      tags:
      - tag
      description: 获取单个标签
      responses:
        "200":
          description: 请求成功
        "1102":
          description: 请求出错
    put:
      tags:
      - tag
      description: 更新标签
      operationId: TagController.更新标签
      parameters:
      - in: path
        name: id
        description: 标签id
        required: true
        type: string
        default: 标签id
      - in: formData
        name: tagName
        description: 标签名字
        required: true
        type: string
        default: javascript
      responses:
        "200":
          description: 请求成功
        "1101":
          description: 外部传入参数错误
        "1102":
          description: 请求出错
        "1108":
          description: 标签名已存在
  /user/:
    get:
      tags:
      - user
      description: 获取用户列表的
      responses:
        "200":
          description: 请求成功
        "1102":
          description: 请求出错
    post:
      tags:
      - user
      description: 创建用户
      operationId: UserController.创建用户
      parameters:
      - in: formData
        name: username
        description: 用户名
        required: true
        type: string
        default: ant
      - in: formData
        name: password
        description: 密码
        required: true
        type: string
        default: "123"
      responses:
        "200":
          description: 请求成功
        "1101":
          description: 外部传入参数错误
        "1102":
          description: 请求出错
        "1103":
          description: 用户名已存在
  /user/{id}:
    get:
      tags:
      - user
      description: 获取单个用户
      responses:
        "200":
          description: 请求成功
        "1102":
          description: 请求出错
    put:
      tags:
      - user
      description: 更新用户信息
      operationId: UserController.更新用户信息
      parameters:
      - in: path
        name: id
        description: 用户id
        required: true
        type: string
        default: "1"
      - in: formData
        name: username
        description: 用户名
        required: true
        type: string
        default: ant
      responses:
        "200":
          description: 请求成功
        "1101":
          description: 外部传入参数错误
        "1102":
          description: 请求出错
        "1103":
          description: 用户名已存在
tags:
- name: user
  description: |
    Operations about User
- name: tag
  description: |
    Operations about Tag
- name: category
  description: |
    Operations about Category
- name: article
  description: |
    Operations about Article
- name: login
  description: |
    Operations about Logout
- name: logout
  description: |
    Operations about Logout
